version: '3.4'

services:
  mongo:
    image: mongo:5.0.2
    restart: "on-failure:10"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: web
      MONGO_INITDB_DATABASE: web
    ports:
      - '27123:27017'
    volumes:
      - 'mongo-data:/data/db'
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  backend:
    build: ./vinhul-backend
    restart: "always"
    depends_on:
      - mongo
    ports:
      - '14001:8080'
    environment:
      DB_USER: root
      DB_PASS: web
      DB_NAME: web
      DB_HOST: mongo:27017
      PORT: 8080

  frontend:
    build: ./vinhul-frontend
    restart: "always"
    depends_on:
      - mongo
    ports:
      - '14000:80'


volumes:
  mongo-data: